/**
 * Auto-generated by tools/generateApiRoutes.ts — do not edit manually.
 *
 * **Jump to handler:** hover the symbol → in the JSDoc popup, click *Open route handler*.
 * If the link fails, use Quick Open (Ctrl/Cmd+P) with the path on the last JSDoc line.
 */

/**
 * API path: `/api/ai/completions`
 *
 * @see [src/app/api/ai/completions/route.ts](../../src/app/api/ai/completions/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/ai/completions/route.ts`
 */
export const API_AI_COMPLETIONS = '/api/ai/completions' as const;

/**
 * API path: `/api/callback`
 *
 * @see [src/app/api/callback/route.ts](../../src/app/api/callback/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/callback/route.ts`
 */
export const API_CALLBACK = '/api/callback' as const;

/**
 * API path: `/api/locales/json`
 *
 * @see [src/app/api/locales/json/route.ts](../../src/app/api/locales/json/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/locales/json/route.ts`
 */
export const API_LOCALES_JSON = '/api/locales/json' as const;

/**
 * API path: `/api/openapi`
 *
 * @see [src/app/api/openapi/route.ts](../../src/app/api/openapi/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/openapi/route.ts`
 */
export const API_OPENAPI = '/api/openapi' as const;

/**
 * API path: `/api/reference`
 *
 * @see [src/app/api/reference/route.ts](../../src/app/api/reference/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/reference/route.ts`
 */
export const API_REFERENCE = '/api/reference' as const;

/**
 * API path: `/api/user/login`
 *
 * @see [src/app/api/user/login/route.ts](../../src/app/api/user/login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/login/route.ts`
 */
export const API_USER_LOGIN = '/api/user/login' as const;

/**
 * API path: `/api/user/logout`
 *
 * @see [src/app/api/user/logout/route.ts](../../src/app/api/user/logout/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/logout/route.ts`
 */
export const API_USER_LOGOUT = '/api/user/logout' as const;

/**
 * API path: `/api/user/register`
 *
 * @see [src/app/api/user/register/route.ts](../../src/app/api/user/register/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/register/route.ts`
 */
export const API_USER_REGISTER = '/api/user/register' as const;

/**
 * API path: `/api/user/session`
 *
 * @see [src/app/api/user/session/route.ts](../../src/app/api/user/session/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/session/route.ts`
 */
export const API_USER_SESSION = '/api/user/session' as const;

export type ApiRoutePath =
  | typeof API_AI_COMPLETIONS
  | typeof API_CALLBACK
  | typeof API_LOCALES_JSON
  | typeof API_OPENAPI
  | typeof API_REFERENCE
  | typeof API_USER_LOGIN
  | typeof API_USER_LOGOUT
  | typeof API_USER_REGISTER
  | typeof API_USER_SESSION;
