/**
 * Auto-generated by tools/generateApiRoutes.ts — do not edit manually.
 *
 * **Jump to handler:** hover the symbol → in the JSDoc popup, click *Open route handler*.
 * If the link fails, use Quick Open (Ctrl/Cmd+P) with the path on the last JSDoc line.
 */

/**
 * API path: `/api/callback/email-login`
 *
 * @see [src/app/api/callback/email-login/route.ts](../../src/app/api/callback/email-login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/callback/email-login/route.ts`
 */
export const API_CALLBACK_EMAIL_LOGIN = '/api/callback/email-login' as const;

/**
 * API path: `/api/callback/provider-login`
 *
 * @see [src/app/api/callback/provider-login/route.ts](../../src/app/api/callback/provider-login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/callback/provider-login/route.ts`
 */
export const API_CALLBACK_PROVIDER_LOGIN =
  '/api/callback/provider-login' as const;

/**
 * API path: `/api/locales/json`
 *
 * @see [src/app/api/locales/json/route.ts](../../src/app/api/locales/json/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/locales/json/route.ts`
 */
export const API_LOCALES_JSON = '/api/locales/json' as const;

/**
 * API path: `/api/user/login`
 *
 * @see [src/app/api/user/login/route.ts](../../src/app/api/user/login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/login/route.ts`
 */
export const API_USER_LOGIN = '/api/user/login' as const;

/**
 * API path: `/api/user/login/provider`
 *
 * @see [src/app/api/user/login/provider/route.ts](../../src/app/api/user/login/provider/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/login/provider/route.ts`
 */
export const API_USER_LOGIN_PROVIDER = '/api/user/login/provider' as const;

/**
 * API path: `/api/user/logout`
 *
 * @see [src/app/api/user/logout/route.ts](../../src/app/api/user/logout/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/logout/route.ts`
 */
export const API_USER_LOGOUT = '/api/user/logout' as const;

/**
 * API path: `/api/user/otp/login`
 *
 * @see [src/app/api/user/otp/login/route.ts](../../src/app/api/user/otp/login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/otp/login/route.ts`
 */
export const API_USER_OTP_LOGIN = '/api/user/otp/login' as const;

/**
 * API path: `/api/user/otp/verify`
 *
 * @see [src/app/api/user/otp/verify/route.ts](../../src/app/api/user/otp/verify/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/otp/verify/route.ts`
 */
export const API_USER_OTP_VERIFY = '/api/user/otp/verify' as const;

/**
 * API path: `/api/user/register`
 *
 * @see [src/app/api/user/register/route.ts](../../src/app/api/user/register/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/register/route.ts`
 */
export const API_USER_REGISTER = '/api/user/register' as const;

/**
 * API path: `/api/user/session`
 *
 * @see [src/app/api/user/session/route.ts](../../src/app/api/user/session/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/session/route.ts`
 */
export const API_USER_SESSION = '/api/user/session' as const;

export type ApiRoutePath =
  | typeof API_CALLBACK_EMAIL_LOGIN
  | typeof API_CALLBACK_PROVIDER_LOGIN
  | typeof API_LOCALES_JSON
  | typeof API_USER_LOGIN
  | typeof API_USER_LOGIN_PROVIDER
  | typeof API_USER_LOGOUT
  | typeof API_USER_OTP_LOGIN
  | typeof API_USER_OTP_VERIFY
  | typeof API_USER_REGISTER
  | typeof API_USER_SESSION;
