name: Release sub packages

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - packages/**

jobs:
  release-pull-request:
    if: |
      github.event.pull_request.merged == true && 
      !contains(github.event.pull_request.labels.*.name, 'CI-Release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: ${{ github.head_ref || github.ref_name }}

      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.0'

      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build

      - name: Release Pull Request
        run: node packages/fe-release/dist/cli.js -V -P --githubPR.push-change-labels --workspaces.change-labels=${{join(github.event.pull_request.labels.*.name,',')}} --changelog.ignore-non-updated-packages
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}

  release:
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'CI-Release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: ${{ github.head_ref || github.ref_name }}

      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.0'

      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build

      - name: Create tag and publish
        run: node packages/fe-release/dist/cli.js -V --changelog.skip-changeset --workspaces.change-labels=${{join(github.event.pull_request.labels.*.name,',')}}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
