packages:
  - packages/*
  - examples/*

peerDependencyRules:
  allowedVersions:
    eslint: '10'

overrides:
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  typescript: ~6.0.3
  '@typescript-eslint/types': ^8.60.1
  '@typescript-eslint/utils': ^8.60.1
  '@typescript-eslint/scope-manager': ^8.60.1
  '@typescript-eslint/typescript-estree': ^8.60.1
  '@typescript-eslint/parser': ^8.60.1

patchedDependencies:
  '@qlover/corekit-bridge': examples/browser-plugin-seed/patches/@qlover__corekit-bridge.patch
  '@qlover/fe-corekit': examples/browser-plugin-seed/patches/@qlover__fe-corekit.patch
