import type { Metadata } from 'next';
import '@/styles/css/index.css';
import { themeConfig } from '@config/theme';
import BaseHeader from '@/uikit/components/BaseHeader';
import { headers } from 'next/headers';
import { i18nConfig } from '@config/i18n';
import { SupportedLocale } from '@/base/port/I18nServiceInterface';
import { ComboProvider } from '@/uikit/components/ComboProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

async function getLanguage(): Promise<SupportedLocale> {
  const headersList = await headers();
  const acceptLanguage = headersList.get('accept-language') || '';
  const preferredLanguage = acceptLanguage
    .split(',')[0]
    .split('-')[0] as SupportedLocale;
  return i18nConfig.supportedLngs.includes(preferredLanguage)
    ? preferredLanguage
    : i18nConfig.fallbackLng;
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = await getLanguage();

  return (
    <html lang={lang} suppressHydrationWarning>
      <body>
        <ComboProvider themeConfig={themeConfig}>
          <div className="min-h-screen bg-secondary">
            <BaseHeader />

            {children}
          </div>
        </ComboProvider>
      </body>
    </html>
  );
}
