import type { Metadata } from 'next';
import '@/styles/css/index.css';
import { ThemeProvider } from 'next-themes';
import { themeConfig } from '@config/theme';
import BaseHeader from '@/uikit/components/BaseHeader';
import { AntdThemeProvider } from '@brain-toolkit/antd-theme-override/react';
import { BootstrapsApp } from '@/uikit/components/BootstrapsApp';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AntdThemeProvider
          theme={{
            cssVar: {
              key: 'fe-theme',
              prefix: 'fe'
            }
          }}
        >
          <ThemeProvider
            attribute={themeConfig.domAttribute}
            defaultTheme={themeConfig.defaultTheme}
            enableSystem
            enableColorScheme={false}
            storageKey={themeConfig.storageKey}
          >
            <BootstrapsApp>
              <div className="min-h-screen bg-secondary">
                <BaseHeader />

                {children}
              </div>
            </BootstrapsApp>
          </ThemeProvider>
        </AntdThemeProvider>
      </body>
    </html>
  );
}
