/**
 * Locale JSON is generated by ts2locales and gitignored (`public/locales`).
 * Ambient modules keep `tsc` happy when the files are not present yet.
 */
declare module '@locales/en.json' {
  const messages: Record<string, string>;
  export = messages;
}

declare module '@locales/zh.json' {
  const messages: Record<string, string>;
  export = messages;
}
