import { mkdirSync, writeFileSync } from 'fs';
import { dirname, isAbsolute, join } from 'path';
import { generateThemeCSS } from '@qlover/tailwind-theme';
import { themeConfig } from '../shared/config/theme';

export type GenerateAppThemeCssOptions = {
  /**
   * Output path relative to `projectRoot`, or absolute.
   * Default: `src/styles/generated/theme.css`.
   */
  outFile?: string;
};

const DEFAULT_OUT_FILE = join('src', 'styles', 'generated', 'theme.css');

/**
 * Emit a slim theme.css for this app's `supportedThemes` only
 * (drops unused package demo themes like amber/forest/ocean).
 */
export function generateAppThemeCss(
  projectRoot: string = process.cwd(),
  options?: GenerateAppThemeCssOptions
): string {
  const relativeOut = options?.outFile ?? DEFAULT_OUT_FILE;
  const outPath = isAbsolute(relativeOut)
    ? relativeOut
    : join(projectRoot, relativeOut);

  const css = generateThemeCSS({
    includeThemes: [...themeConfig.supportedThemes],
    defaultTheme: 'light'
  });

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(
    outPath,
    `/* Auto-generated by tools/generateAppThemeCss.ts — do not edit */\n${css}`,
    'utf-8'
  );

  console.log(`✅ App theme CSS generated at ${outPath}`);
  return outPath;
}
