name: FE Build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[From bot]') == false &&
      contains(github.event.head_commit.message, 'chore(tag)') == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build dist
        run: yarn build
