name: CD

on:
  push:
    branches:
      - base
  pull_request:
    branches:
      - base
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Yarn and dependencies
      - run: npm install yarn -g && yarn -v && yarn

      - name: lint-test-build
      # https://github.com/semantic-release/git/issues/209
      - run: yarn lint
      - run: yarn test
      - run: yarn build
