name: CD

on:
  push:
    branches:
      - base
  pull_request:
    branches:
      - base
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      # https://github.com/semantic-release/git/issues/209
      - run: npm run lint
      - run: npm run test
