name: CI

on:
  push:
    branches:
      - base
  pull_request:
    branches:
      - base
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Yarn and dependencies
        run: npm install yarn -g && yarn -v && yarn

      - name: Lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: yarn build
