name: General check

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  check-code:
    # if not CI-Release label, then run check
    if: |
      !contains(github.event.pull_request.labels.*.name, 'CI-Release')
    runs-on: ubuntu-latest

    steps:
      # - name: Print GitHub Event Information
      #   run: echo "${{ toJson(github.event.pull_request) }}" > event.json
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.0'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
      # - run: pnpm nx:build --base=origin/${{ github.base_ref }} --head=HEAD
      - run: pnpm build

      - name: Check packages
        run: |
          git fetch origin ${{ github.base_ref }}
          pnpm run check-packages -V -r ${{ github.repository }} -b ${{ github.base_ref }} -n ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
