name: General check

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  check-code:
    if: |
      !contains(github.event.pull_request.title, 'chore(tag):') && 
      !contains(join(github.event.pull_request.commits.*.message, ' '), 'chore(tag):')
    runs-on: ubuntu-latest

    steps:
      # - name: Print GitHub Event Information
      #   run: echo "${{ toJson(github.event) }}" > event.json
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'

      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: NX Build
        run: pnpm nx:build

      - name: Check packages
        run: |
          git fetch origin ${{ github.base_ref }}
          pnpm check-packages -- -V -r ${{ github.repository }} -b ${{ github.base_ref }} -n ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
