name: General check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-code:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'CI-Release')
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set SHAs for Nx affected
        uses: nrwl/nx-set-shas@v4
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile

      - name: Build (affected)
        run: pnpm nx affected:build --parallel --maxParallel=4

      - run: pnpm lint
      - run: pnpm test

      # 【建议】确认是否真的需要全局 rebuild，通常不需要
      # - run: pnpm rebuild

      - name: Check packages
        if: github.event.pull_request.base.ref == 'master'
        run: |
          git fetch origin ${{ github.base_ref }}
          pnpm run check-packages -V -r ${{ github.repository }} -b ${{ github.base_ref }} -n ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
