name: General check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-code:
    # Skip if has CI-Release label
    if: |
      !contains(github.event.pull_request.labels.*.name, 'CI-Release')
    runs-on: ubuntu-latest

    steps:
      # - name: Print GitHub Event Information
      #   run: echo "${{ toJson(github.event.pull_request) }}" > event.json
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.0'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
      
      # CI environment does not have .nx/cache cache, and each new build cannot read the cache, 
      # if there is no cache from the last time, then other packages will not produce dist, but the local will read it directly from .nx/cache
      # TODO: solve nx cache, use incremental build
      # - run: pnpm nx:build --base=origin/${{ github.base_ref }} --head=HEAD --skip-nx-cache
      - run: pnpm nx:build:force

      - run: pnpm rebuild

      # Only run package checks when targeting master
      - name: Check packages
        if: github.event.pull_request.base.ref == 'master'
        run: |
          git fetch origin ${{ github.base_ref }}
          pnpm run check-packages -V -r ${{ github.repository }} -b ${{ github.base_ref }} -n ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
