name: Release Fe-Scripts

on:
  workflow_dispatch:
  pull_request:
    branches:
      - merge-packages-test-cicd

jobs:
  # create-release-fe-scripts-pr:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Config Git
  #       run: |
  #         git config --global user.name "github-actions[bot]"
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"  

  #     - name: Install Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '18.19.0'


  #     - name: Install dependencies
  #       run: |
  #         npm install -g yarn
  #         yarn

  #     - name: Lint
  #       run: yarn lint

  #     - name: Test
  #       run: yarn test

  #     - name: Build dist
  #       run: yarn build

  #     - name: Create release PR
  #       run: |
  #         cd packages/fe-scripts
  #         npm run release-pr -- -V --dryrun
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
  #         PAT_TOKEN: ${{ secrets.PAT_TOKEN }} 

  release-fe-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build dist
        run: yarn build

      - name: Create tag and publish
        run: |
          cd packages/fe-scripts
          npm run release -- -V --dryrun
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }} 